---
title: "Project3"
author: "Avery Davidowitz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


## Import libraries and 
```{r}
library(tidyverse)
library(DBI)
```

## Establish database connection
Must have RMySQL pakage installed
```{r}
user_name <- .rs.askForPassword("Enter the Database user name")
password <- .rs.askForPassword("Enter the Database password")
#con <- dbConnect(RMySQL::MySQL(), timeout = 30,
#                 host = "35.199.43.105", port = 3306, Database = "ds_jobs", UID = user_name, PWD = password)
con <- dbConnect(RMySQL::MySQL(), 
                 dbname = "ds_jobs", 
                 host = "35.199.43.105", 
                 port = 3306,
                 user = user_name,
                 password = password)
```

## Test connection
```{r}
odbc::dbSendStatement(con, "INSERT IGNORE INTO location (CITY, STATE, POPULATION) VALUES ('New York', 'NY', 20201249
)")
test_select <- odbc::dbGetQuery(con, "SELECT * FROM ds_jobs.location;")
print(test_select)
```



## Good Citizen
```{r}
dbDisconnect(con)
```